/**
 * Workflow Templates
 *
 * Each template defines the operator-facing language for a System Profile's
 * Command Center workflow. Templates drive:
 *   - Step labels and subtitles (display only)
 *   - Agent action button labels (display only — task_type and agent_name are unchanged)
 *   - CommandContextCard chip labels and next-action step label
 *   - Step 1 guidance text
 *   - Agent fit hints (visual muting for off-profile agents)
 *
 * Nothing here changes backend behavior, API calls, agent execution,
 * module defaults, or data filters. It is presentation/configuration only.
 *
 * agentFit: if false, the corresponding action button renders muted (opacity-60)
 * with a tooltip hint. It remains clickable — no behavior change.
 */

export const WORKFLOW_TEMPLATES = {
  // -------------------------------------------------------------------------
  // Executive Growth Engine  (media_growth / content + outreach)
  // -------------------------------------------------------------------------
  executive_growth: {
    step1Guidance:
      "Use the Executive Growth Engine to discover media partnerships, content opportunities, and distribution channels. Review and approve agent-generated plans before queuing assets for manual distribution.",
    steps: {
      1: { label: "Select System",          subtitle: "Confirm the active executive brand and mode before starting." },
      2: { label: "Discover Opportunities", subtitle: "Research media partners, content angles, and distribution targets." },
      3: { label: "Review Agent Work",      subtitle: "Monitor the active discovery or content generation run." },
      4: { label: "Review & Approve",       subtitle: "Approve, revise, or reject generated plans, scripts, and outlines." },
      5: { label: "Queue for Distribution", subtitle: "Approved content is ready for manual scheduling or posting." },
      6: { label: "Audience Engagement",    subtitle: "Track inbound replies, comments, and partner signals." },
      7: { label: "Monetization / CRM",     subtitle: "Sponsorships, guest bookings, and closed partnership opportunities." },
    },
    agentLabels: {
      run_outreach:     "Research Media Partners",
      run_followup:     "Follow Up on Partners",
      generate_content: "Plan Content Assets",
      engage_fans:      "Engage Audience",
    },
    agentFit: {
      run_outreach:     true,
      run_followup:     true,
      generate_content: true,
      engage_fans:      true,
    },
    chips: {
      reviewNeeded: "Review needed",
      readyToSend:  "Queue for distribution",
      responses:    "Audience signals",
      openDeals:    "Open opportunities",
    },
    runCards: [
      {
        id: "content_discovery",
        label: "Content Discovery Run",
        description: "Searches the web (via Tavily) for content relevant to this client's audience and stages candidates as Source Content for review — no automated download, clip, or reuse.",
        icon: "Search",
        agent_name: "trend_discovery",
        task_type: "discover_trends",
        defaultModule: "media_growth",
        defaultPriority: "normal",
        defaultLimit: 5,
        isLive: true,
        modalHint: "This run searches for real, audience-relevant content and stages each result as a Source Content candidate in Campaign Studio → Source Content, tagged third_party_curated with best-effort creator attribution. Nothing is downloaded or reused until you approve it there. The search query is built from this client's Audience and Content Goals fields — set those on the client profile for more relevant results. Requires TAVILY_ENABLED + TAVILY_API_KEY; otherwise this run completes with no candidates.",
        modalFields: [
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 20, defaultValue: 5 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
        ],
      },
      {
        id: "content_asset_creation",
        label: "Content Asset Creation Run",
        description: "Generates scripts, hooks, captions, post concepts, faceless-video prompts, and content briefs.",
        icon: "FileText",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "media_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run generates content assets for your review — scripts, hooks, and briefs appear in Review & Approve. No content is published. A human reviews and approves all outputs.",
        modalFields: [
          { id: "content_format", label: "Content Format", type: "select", options: ["Short-form video script", "LinkedIn post", "Carousel outline", "Newsletter section", "Faceless video prompt", "Mixed"], defaultValue: "Mixed" },
          { id: "platform", label: "Platform", type: "select", options: ["YouTube Shorts", "Instagram", "TikTok", "LinkedIn", "Email newsletter", "All platforms"], defaultValue: "All platforms" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 10 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Repurpose the Maxwell keynote series", defaultValue: "" },
        ],
      },
      {
        id: "media_production_prep",
        label: "Media Production Prep Run",
        description: "Prepares clip/edit instructions, thumbnail ideas, B-roll prompts, audio/video notes, and publishing specs.",
        icon: "Film",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "media_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run prepares production-ready notes and instructions for your media team. Outputs appear in Review & Approve for operator sign-off before handoff to production.",
        modalFields: [
          { id: "source_type", label: "Source Material", type: "select", options: ["Podcast episode", "Keynote recording", "Interview clip", "Live session", "Other"], defaultValue: "Podcast episode" },
          { id: "content_format", label: "Prep Format", type: "select", options: ["Clip / edit instructions", "Thumbnail concepts", "B-roll prompts", "Publishing spec sheet", "Mixed"], defaultValue: "Mixed" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 10 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Prep the Q2 leadership series for production", defaultValue: "" },
        ],
      },
      {
        id: "audience_engagement",
        label: "Audience Engagement Run",
        description: "Reviews comments, DMs, replies, and audience signals to recommend engagement actions.",
        icon: "Users",
        agent_name: "fan_engagement",
        task_type: "engage_fans",
        defaultModule: "media_growth",
        defaultPriority: "normal",
        defaultLimit: 15,
        isLive: true,
        modalHint: "This run scans audience signals and surfaces recommended engagement actions. All actions require human review and approval before any reply or response is sent.",
        modalFields: [
          { id: "platform", label: "Platform", type: "select", options: ["YouTube comments", "Instagram DMs", "TikTok comments", "LinkedIn replies", "All channels"], defaultValue: "All channels" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 15 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Prioritize comments on the latest keynote video", defaultValue: "" },
        ],
      },
      {
        id: "digital_product_offer",
        label: "Digital Product / Offer Run",
        description: "Converts audience demand into lead magnets, micro-products, cohorts, guides, or offers.",
        icon: "Gift",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "media_growth",
        defaultPriority: "normal",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Contractor Growth Engine  (contractor_growth / outreach + followup)
  // -------------------------------------------------------------------------
  contractor_growth: {
    step1Guidance:
      "Use the Contractor Growth Engine to identify local service leads, prepare human-reviewed outreach, and track your B2B pipeline from discovery to booked calls and closed deals.",
    steps: {
      1: { label: "Select System",   subtitle: "Confirm the active business profile before starting." },
      2: { label: "Run Agent",       subtitle: "Start a lead discovery, follow-up, or content generation task." },
      3: { label: "Agent Activity",  subtitle: "Current or most recent run, including timeline and generated outputs." },
      4: { label: "Review Outputs",  subtitle: "Approve, revise, reject, or convert generated work without leaving Workflow." },
      5: { label: "Ready to Send",   subtitle: "Approved drafts are ready for a human to send outside SignalForge." },
      6: { label: "Track Responses", subtitle: "Track response states after a human manually sends outreach." },
      7: { label: "Track Deals",     subtitle: "Review open opportunities and closed wins generated by the workflow." },
    },
    agentLabels: {
      run_outreach:     "Find & Qualify Leads",
      run_followup:     "Follow Up on Leads",
      generate_content: "Generate Outreach Content",
      engage_fans:      "Fan Engagement",
    },
    agentFit: {
      run_outreach:     true,
      run_followup:     true,
      generate_content: true,
      engage_fans:      false,
    },
    chips: {
      reviewNeeded: "Review needed",
      readyToSend:  "Ready to send",
      responses:    "Responses",
      openDeals:    "Open deals",
    },
    runCards: [
      {
        id: "lead_discovery",
        label: "Lead Discovery Run",
        description: "Scans for new local service, construction, or trade leads matching your target profile.",
        icon: "MapPin",
        agent_name: "outreach",
        task_type: "run_outreach",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 20,
        isLive: true,
        modalHint: "This run identifies new leads matching your contractor profile. Results appear in Review Outputs for qualification before any outreach is drafted.",
        modalFields: [
          { id: "service_area", label: "Service Area", type: "text", placeholder: "e.g. Phoenix, AZ metro", defaultValue: "" },
          { id: "lead_type", label: "Lead Type", type: "select", options: ["Roofing", "HVAC", "Plumbing", "Electrical", "General contracting", "Landscaping", "Other"], defaultValue: "General contracting" },
          { id: "source_preference", label: "Source", type: "select", options: ["Google Maps", "Yelp", "HomeAdvisor", "Angi", "Social media", "All sources"], defaultValue: "All sources" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 20 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Focus on residential roofing leads", defaultValue: "" },
        ],
      },
      {
        id: "lead_enrichment_scoring",
        label: "Lead Enrichment & Scoring Run",
        description: "Reviews and scores existing leads, adding firmographic context and priority signals.",
        icon: "Star",
        agent_name: "outreach",
        task_type: "run_outreach",
        defaultModule: "contractor_growth",
        defaultPriority: "high",
        defaultLimit: 15,
        isLive: true,
        modalHint: "This run re-evaluates and scores existing leads with additional context. Scored leads are surfaced for human review and prioritization before outreach begins.",
        modalFields: [
          { id: "service_area", label: "Service Area", type: "text", placeholder: "e.g. Phoenix, AZ metro (optional)", defaultValue: "" },
          { id: "lead_type", label: "Lead Type", type: "select", options: ["Roofing", "HVAC", "Plumbing", "Electrical", "General contracting", "Landscaping", "Other"], defaultValue: "General contracting" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 15 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "high" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Focus on high-value commercial leads", defaultValue: "" },
        ],
      },
      {
        id: "outreach_draft",
        label: "Outreach Draft Run",
        description: "Generates personalized outreach messages for reviewed and approved leads.",
        icon: "Mail",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run generates outreach drafts for qualified leads. All drafts appear in Review Outputs for operator approval. No message is sent — a human sends approved outreach manually.",
        modalFields: [
          { id: "content_format", label: "Outreach Channel", type: "select", options: ["Email", "SMS", "LinkedIn message", "Voicemail script"], defaultValue: "Email" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 10 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Seasonal roofing push, Q2 HVAC campaign", defaultValue: "" },
        ],
      },
      {
        id: "followup",
        label: "Follow-Up Run",
        description: "Prepares follow-up sequences for unanswered or warm outreach threads.",
        icon: "MessageCircle",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run prepares follow-up messages for contacts who haven't responded or have expressed interest. All follow-ups require human approval before sending.",
        modalFields: [
          { id: "content_format", label: "Follow-Up Channel", type: "select", options: ["Email follow-up", "SMS follow-up", "LinkedIn follow-up", "Phone script"], defaultValue: "Email follow-up" },
          { id: "limit", label: "Output Quantity", type: "number", min: 1, max: 50, defaultValue: 10 },
          { id: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"], defaultValue: "normal" },
          { id: "notes", label: "Campaign context", type: "text", placeholder: "e.g. Follow up on unanswered roofing estimates", defaultValue: "" },
        ],
      },
      {
        id: "estimate_deal_tracking",
        label: "Estimate & Deal Tracking Run",
        description: "Prepares proposal copy and tracks pipeline stage for open estimates and active deals.",
        icon: "DollarSign",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Creator Monetization Engine  (artist_growth / content + fan_engagement)
  // -------------------------------------------------------------------------
  creator_monetization: {
    step1Guidance:
      "Use the Creator Monetization Engine to discover fan engagement opportunities, create release content, pitch curators and venues, and track bookings and revenue for your artist campaign.",
    steps: {
      1: { label: "Select System",          subtitle: "Confirm the active artist or creator profile before starting." },
      2: { label: "Run Campaign",           subtitle: "Run fan engagement, opportunity discovery, or content creation for this release moment." },
      3: { label: "Campaign Activity",      subtitle: "Monitor the active agent run and see generated campaign outputs." },
      4: { label: "Review & Approve",       subtitle: "Review generated pitches, content drafts, and approval requests." },
      5: { label: "Queue for Release",      subtitle: "Approved content or outreach is ready for manual release." },
      6: { label: "Fan & Industry Replies", subtitle: "Track responses from fans, curators, venues, and media contacts." },
      7: { label: "Bookings & Revenue",     subtitle: "Review show bookings, deals, and closed opportunities." },
    },
    agentLabels: {
      run_outreach:     "Find Opportunities",
      run_followup:     "Follow Up on Pitches",
      generate_content: "Create Content",
      engage_fans:      "Engage Fans",
    },
    agentFit: {
      run_outreach:     true,
      run_followup:     true,
      generate_content: true,
      engage_fans:      true,
    },
    chips: {
      reviewNeeded: "Review needed",
      readyToSend:  "Queue for release",
      responses:    "Fan & industry replies",
      openDeals:    "Bookings & deals",
    },
    runCards: [
      {
        id: "fan_engagement_scan",
        label: "Fan Engagement Scan",
        description: "Reviews fan comments, DMs, and audience signals to surface engagement opportunities.",
        icon: "Music2",
        agent_name: "fan_engagement",
        task_type: "engage_fans",
        defaultModule: "artist_growth",
        defaultPriority: "normal",
        defaultLimit: 20,
        isLive: true,
        modalHint: "This run scans fan signals across channels and surfaces recommended engagement actions. All engagement responses require human review and approval before being sent.",
      },
      {
        id: "opportunity_discovery",
        label: "Opportunity Discovery Run",
        description: "Researches curators, venues, playlist placements, sync opportunities, and media contacts.",
        icon: "Compass",
        agent_name: "outreach",
        task_type: "run_outreach",
        defaultModule: "artist_growth",
        defaultPriority: "normal",
        defaultLimit: 20,
        isLive: true,
        modalHint: "This run identifies industry targets for your current campaign — curators, venues, sync opportunities, and media contacts. Results land in Review & Approve for operator qualification.",
      },
      {
        id: "release_content_creation",
        label: "Release Content Creation Run",
        description: "Generates captions, press angles, playlist pitches, short-form hooks, and release campaign copy.",
        icon: "Newspaper",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "artist_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run generates release campaign content assets for your review — captions, pitches, and copy. Nothing is published. A human reviews and approves all outputs before use.",
      },
      {
        id: "pitch_followup",
        label: "Pitch Follow-Up Run",
        description: "Follows up on open curator, venue, and media outreach to advance the campaign.",
        icon: "Send",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "artist_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run prepares follow-up sequences for open pitch threads. All follow-up messages require human approval before any outreach is sent.",
      },
      {
        id: "bookings_revenue_prep",
        label: "Bookings & Revenue Prep",
        description: "Prepares booking summaries, offer structures, and deal-close messaging for confirmed interest.",
        icon: "TrendingUp",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "artist_growth",
        defaultPriority: "normal",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Investor Outreach Engine  (insurance_growth / outreach + content)
  // -------------------------------------------------------------------------
  investor_outreach: {
    step1Guidance:
      "Use the Investor Outreach Engine to research investor targets, generate narrative-driven pitches and content, and track your capital pipeline from first contact to term sheet.",
    steps: {
      1: { label: "Select System",      subtitle: "Confirm the active capital pipeline before starting." },
      2: { label: "Prospect Investors", subtitle: "Research targets, generate narrative content, and prepare follow-up sequences." },
      3: { label: "Pipeline Activity",  subtitle: "Monitor the active prospecting run and see generated outputs." },
      4: { label: "Review & Approve",   subtitle: "Review and approve outreach plans and investor narrative drafts." },
      5: { label: "Ready to Pitch",     subtitle: "Approved investor outreach is ready for human delivery." },
      6: { label: "Track Responses",    subtitle: "Track investor replies, meeting requests, and interest signals." },
      7: { label: "Capital Pipeline",   subtitle: "Review open term sheets, scheduled meetings, and closed commitments." },
    },
    agentLabels: {
      run_outreach:     "Research Investor Targets",
      run_followup:     "Follow Up on Prospects",
      generate_content: "Generate Narrative Content",
      engage_fans:      "Fan Engagement",
    },
    agentFit: {
      run_outreach:     true,
      run_followup:     true,
      generate_content: true,
      engage_fans:      false,
    },
    chips: {
      reviewNeeded: "Review needed",
      readyToSend:  "Ready to pitch",
      responses:    "Investor responses",
      openDeals:    "Open opportunities",
    },
    runCards: [
      {
        id: "investor_research",
        label: "Investor Research Run",
        description: "Identifies and qualifies investor targets by thesis, stage, sector, and recent activity.",
        icon: "Search",
        agent_name: "outreach",
        task_type: "run_outreach",
        defaultModule: "insurance_growth",
        defaultPriority: "normal",
        defaultLimit: 20,
        isLive: true,
        modalHint: "This run researches and qualifies investor targets for your capital raise. Results appear in Review & Approve for operator qualification before any outreach is drafted.",
      },
      {
        id: "narrative_content",
        label: "Narrative & Content Run",
        description: "Generates investor narrative copy, email sequences, and pitch deck supporting content.",
        icon: "FileText",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "insurance_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run generates narrative-driven investor content for your review — outreach emails, pitch angles, and supporting copy. No content is sent without human approval.",
      },
      {
        id: "prospect_followup",
        label: "Prospect Follow-Up Run",
        description: "Prepares follow-up messaging for investors who have not responded or expressed early interest.",
        icon: "MessageCircle",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "insurance_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run prepares follow-up sequences for open investor prospect threads. All messages require human approval and are sent manually outside SignalForge.",
      },
      {
        id: "meeting_prep",
        label: "Meeting Prep Run",
        description: "Drafts pre-meeting research summaries, likely objections, and talking points for scheduled calls.",
        icon: "Compass",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "insurance_growth",
        defaultPriority: "high",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
      {
        id: "term_sheet_pipeline",
        label: "Term Sheet Pipeline Review",
        description: "Tracks active term sheet discussions and assists with close-sequence messaging.",
        icon: "TrendingUp",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "insurance_growth",
        defaultPriority: "high",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Recruiting Pipeline Engine  (contractor_growth / followup + outreach)
  // -------------------------------------------------------------------------
  recruiting_pipeline: {
    step1Guidance:
      "Use the Recruiting Pipeline Engine to source candidates, prepare human-reviewed outreach, and track your talent pipeline from initial discovery to placement.",
    steps: {
      1: { label: "Select System",       subtitle: "Confirm the active talent pipeline before starting." },
      2: { label: "Source Candidates",   subtitle: "Identify, research, and prepare candidate outreach for human review." },
      3: { label: "Pipeline Activity",   subtitle: "Monitor the active sourcing run and see generated outputs." },
      4: { label: "Review & Approve",    subtitle: "Review sourced candidates and generated outreach for operator approval." },
      5: { label: "Ready to Reach Out",  subtitle: "Approved candidate outreach is ready for a human recruiter." },
      6: { label: "Candidate Responses", subtitle: "Track replies, interest signals, and scheduling requests." },
      7: { label: "Placements",          subtitle: "Review placed candidates and closed hiring outcomes." },
    },
    agentLabels: {
      run_outreach:     "Source Candidates",
      run_followup:     "Follow Up on Candidates",
      generate_content: "Generate Candidate Content",
      engage_fans:      "Fan Engagement",
    },
    agentFit: {
      run_outreach:     true,
      run_followup:     true,
      generate_content: true,
      engage_fans:      false,
    },
    chips: {
      reviewNeeded: "Review needed",
      readyToSend:  "Ready to reach out",
      responses:    "Candidate responses",
      openDeals:    "Placements",
    },
    runCards: [
      {
        id: "candidate_sourcing",
        label: "Candidate Sourcing Run",
        description: "Identifies qualified candidates matching the active role profile and sourcing criteria.",
        icon: "Users",
        agent_name: "outreach",
        task_type: "run_outreach",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 20,
        isLive: true,
        modalHint: "This run identifies and qualifies candidates for your active role. Results appear in Review & Approve for recruiter sign-off before any outreach is drafted.",
      },
      {
        id: "outreach_generation",
        label: "Outreach Generation Run",
        description: "Generates personalized candidate outreach for sourced and approved candidates.",
        icon: "Mail",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run generates personalized outreach for approved candidates. All messages are reviewed and sent manually by a human recruiter — nothing is auto-sent.",
      },
      {
        id: "candidate_followup",
        label: "Candidate Follow-Up Run",
        description: "Prepares follow-up sequences for unanswered or warm candidate threads.",
        icon: "MessageCircle",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "This run prepares follow-up messages for candidates who haven't responded or have expressed interest. All follow-ups require recruiter review before sending.",
      },
      {
        id: "interview_prep",
        label: "Interview Prep Run",
        description: "Generates interview question sets, evaluation scorecards, and hiring manager briefs.",
        icon: "FileText",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
      {
        id: "placement_close",
        label: "Placement & Close Run",
        description: "Tracks candidate pipeline stage, prepares offer messaging, and logs closed placements.",
        icon: "Star",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "contractor_growth",
        defaultPriority: "high",
        defaultLimit: 5,
        isLive: false,
        modalHint: "",
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Custom  (no preset — generic fallback, exactly matches prior hardcoded labels)
  // -------------------------------------------------------------------------
  custom: {
    step1Guidance:
      "Profile selection is currently display-only. Agent module selection remains inside the run modal.",
    steps: {
      1: { label: "Select System",   subtitle: "Confirm the active business profile before starting." },
      2: { label: "Run Agent",       subtitle: "Start the same safe Agent Tasks dry-run from the top of the workflow." },
      3: { label: "Agent Activity",  subtitle: "Current or most recent run, including timeline and generated outputs." },
      4: { label: "Review Outputs",  subtitle: "Approve, revise, reject, or convert generated work without leaving Workflow." },
      5: { label: "Ready to Send",   subtitle: "Approved drafts are ready for a human to send outside SignalForge." },
      6: { label: "Responses",       subtitle: "Track response states after a human manually sends outreach." },
      7: { label: "Deals",           subtitle: "Review open opportunities and closed wins generated by the workflow." },
    },
    agentLabels: {
      run_outreach:     "Run Outreach",
      run_followup:     "Run Follow-up",
      generate_content: "Generate Content",
      engage_fans:      "Fan Engagement",
    },
    agentFit: {
      run_outreach:     true,
      run_followup:     true,
      generate_content: true,
      engage_fans:      true,
    },
    chips: {
      reviewNeeded: "Review needed",
      readyToSend:  "Ready to send",
      responses:    "Responses",
      openDeals:    "Open deals",
    },
    runCards: [
      {
        id: "run_outreach",
        label: "Run Outreach",
        description: "Discover and queue new leads or contacts for outreach.",
        icon: "Megaphone",
        agent_name: "outreach",
        task_type: "run_outreach",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "Runs a dry-run outreach task. Outputs are created for review — no message is sent.",
      },
      {
        id: "run_followup",
        label: "Run Follow-up",
        description: "Prepare follow-up sequences for existing contacts and threads.",
        icon: "MessageCircle",
        agent_name: "followup",
        task_type: "run_followup",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "Runs a dry-run follow-up task. Generated messages appear in Review Outputs — no message is sent.",
      },
      {
        id: "generate_content",
        label: "Generate Content",
        description: "Generate outreach drafts, message assets, and content for review.",
        icon: "Newspaper",
        agent_name: "content",
        task_type: "generate_content",
        defaultModule: "contractor_growth",
        defaultPriority: "normal",
        defaultLimit: 10,
        isLive: true,
        modalHint: "Runs a content generation task. All outputs appear in Review Outputs for human review and approval.",
      },
      {
        id: "engage_fans",
        label: "Fan Engagement",
        description: "Scan and respond to audience engagement signals.",
        icon: "Music2",
        agent_name: "fan_engagement",
        task_type: "engage_fans",
        defaultModule: "artist_growth",
        defaultPriority: "normal",
        defaultLimit: 15,
        isLive: true,
        modalHint: "Scans for fan engagement signals and surfaces recommended actions. All responses require human approval.",
      },
    ],
  },
};

/** Safe fallback — always resolves to a fully-formed template. */
export const DEFAULT_TEMPLATE = WORKFLOW_TEMPLATES.custom;
